-- AlterTable
ALTER TABLE "Prediction" ALTER COLUMN "pointsAwarded" SET DEFAULT 0,
ALTER COLUMN "pointsAwarded" SET DATA TYPE DOUBLE PRECISION;

-- AlterTable
ALTER TABLE "UserMatchState" ALTER COLUMN "score" SET DEFAULT 0,
ALTER COLUMN "score" SET DATA TYPE DOUBLE PRECISION;
