-- AlterEnum
ALTER TYPE "MatchStatus" ADD VALUE IF NOT EXISTS 'HALF_TIME';

-- AlterTable
ALTER TABLE "Match" ADD COLUMN IF NOT EXISTS "clockSeconds" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "Match" ADD COLUMN IF NOT EXISTS "clockRunning" BOOLEAN NOT NULL DEFAULT false;
