import type { EventRecord, Match, Round } from "./types.js";
import { matchDurationMinutes } from "./config.js";

export const formatStatus = (status: Match["status"]) => status.replace(/_/g, " ");
export const statusClass = (status: Match["status"]) => status === "LIVE" ? "bg-red-400 text-black" : status === "HALF_TIME" ? "bg-yellow-300 text-black" : status === "OPEN" ? "bg-lime-300 text-black" : status === "FINISHED" ? "bg-white text-black" : "bg-white/10 text-white/70";
export const eventIcon = (type: string) => type === "GOAL" ? "⚽" : type === "YELLOW_CARD" ? "🟨" : type === "RED_CARD" ? "🟥" : type === "CORNER" ? "🚩" : type === "SUBSTITUTION" ? "🔄" : "•";
export const formatPrediction = (value: string) => value.toLowerCase().split("_").map((part) => part.charAt(0).toUpperCase() + part.slice(1)).join(" ");
export const formatScore = (score: number) => Number.isInteger(score) ? String(score) : score.toFixed(1);
export function formatDuration(ms: number) { const value = Math.max(0, Math.floor(ms / 1000)); const h = Math.floor(value / 3600); const m = Math.floor((value % 3600) / 60); const s = value % 60; return h > 0 ? `${h}h ${String(m).padStart(2, "0")}m` : `${String(m).padStart(2, "0")}:${String(s).padStart(2, "0")}`; }
export function getEffectiveClockSeconds(match: Match, now: number) { if (!match.clockRunning || !match.clockUpdatedAt) return match.clockSeconds; const anchor = new Date(match.clockUpdatedAt).getTime(); return Number.isFinite(anchor) ? match.clockSeconds + Math.max(0, Math.floor((now - anchor) / 1000)) : match.clockSeconds; }
export function isHalfTime(match: Match, now: number) { const seconds = getEffectiveClockSeconds(match, now); if (match.clockRunning && seconds > 2700) return false; if (match.status === "HALF_TIME") return true; if (match.status !== "LIVE") return false; if (seconds >= 2700 && seconds < 2760 && !match.clockRunning) return true; const kickoff = new Date(match.startTime).getTime(); return Number.isFinite(kickoff) && match.clockSeconds === 0 && Math.floor((now - kickoff) / 60000) >= 45 && Math.floor((now - kickoff) / 60000) < 65; }
export function getRoundAtTime(match: Match, rounds: Round[], now: number) { if (match.status !== "LIVE" && match.status !== "OPEN" && !match.clockRunning || isHalfTime(match, now)) return null; const seconds = getEffectiveClockSeconds(match, now); const minute = seconds > 0 || match.clockRunning ? Math.floor(seconds / 60) : Math.floor((now - new Date(match.startTime).getTime()) / 60000); if (!Number.isFinite(minute) || minute < 0 || minute >= matchDurationMinutes) return null; return rounds.find((round) => round.number === Math.floor(minute / 3) + 1) ?? null; }
export function getMsUntilRoundEnd(match: Match, round: Round, now: number) { const seconds = getEffectiveClockSeconds(match, now); if (seconds > 0 || match.clockRunning) return Math.max(0, (round.endMinute * 60 - seconds) * 1000); if (match.status === "LIVE") return null; return new Date(match.startTime).getTime() + round.endMinute * 60000 - now; }
export function dedupeTimelineEvents(events: EventRecord[]) { const accepted: EventRecord[] = []; for (const event of events) { const action = event.rawAction.split(" ")[0]?.toLowerCase(); if (["var", "score_adjustment", "action_amend"].includes(action || "")) continue; const duplicate = accepted.some((item) => item.id === event.id || (!event.simulated && !item.simulated && item.eventType === event.eventType && item.minute === event.minute && item.participant === event.participant && Math.abs(new Date(item.createdAt).getTime() - new Date(event.createdAt).getTime()) < 90000)); if (!duplicate) accepted.push(event); } return accepted; }
export const formatMultiplier = (streak: number) => streak >= 5 ? "2" : streak === 4 ? "1.5" : streak === 3 ? "1.25" : streak === 2 ? "1.1" : streak > 0 ? "1" : "0";
export function shouldShowEventNotification(event: EventRecord, shown: Map<string, number>) { const now = Date.now(); const key = [event.matchId, event.eventType, event.minute ?? "-", event.participant ?? "-", event.rawAction].join(":"); const previous = shown.get(key); for (const [storedKey, timestamp] of shown) if (now - timestamp > 90000) shown.delete(storedKey); if (previous && now - previous < 90000) return false; shown.set(key, now); return true; }
export function triggerConfetti(setValue: (value: boolean) => void) { setValue(true); window.setTimeout(() => setValue(false), 1800); }
